config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "ask", to: "questions#ask",       as: :ask
  get "answer", to: "questions#answer", as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @answer = "I don't care, get dressed and go to work!"

    unless params[:question].nil?
      if params[:question] == "I am going to work"
          @answer = " Great!"
      elsif params[:question][-1] == "?"
          @answer = "Silly question, get dressed and go to work!"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Answer</h1>

<div class="m-2 border-start border-3 p-2">
  <h4><%= params[:question] %></h4>
  <h2>-You</h2>
</div>

<div class="bg-warning  m-4 border-start border-success">
  <h4 class="fw-bold"><%= @answer %></h4>
  <p>-Your coach</p>
</div>



<%= link_to "Ask a new question" , ask_path%>

app/views/questions/ask.html.erb
<h1>Ask</h1>

<form action="/answer" data-turbo="false">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>